all:
	g++ codigo.cpp -o programa -I/usr/include/x86_64-linux-gnu -lallegro_ttf -lallegro_font -lallegro_primitives -lallegro
	
	
	
# $(pkg-config --cflags --libs allegro-5 allegro_font-5 allegro_ttf-5 allegro_primitives-5)
